version: '3.9'
services:

#Serveur Web
#############
  web:
  #nginx:
    image: nginx:latest
    container_name: Nginx
    ports:
      - "90:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - 'biblio'

#Serveur Applicatif
####################
  #wsgi:
  app:
    image: tiangolo/meinheld-gunicorn:latest
    container_name: WSGI
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:5000'
    volumes:
      - .:/var/www/html
    environment:
      FLASK_DEBUG: "true"
    networks:
      - 'biblio'

#Serveur BD
############
  db:
    image: mysql:latest
    container_name: MySQL
    ports:
      - 3306
    volumes:
      - './db:/docker-entrypoint-initdb.d'
    restart: 'on-failure'
    environment:
      MYSQL_DATABASE: biblio #ceci vas pouvoir etre consulter dans phpmyadmin
      MYSQL_ROOT_PASSWORD: root
    networks:
      - 'biblio'


#Cache Mémoire
###############
  cache:
    image: redis:latest
    container_name: Redis
    #ports:
    #  - "6379:80"
    # networks:
    #   - frontend
    # deploy:
    #   replicas: 2
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    #   restart_policy:
    #     condition: on-failure

networks:
  biblio:
    driver: bridge  